# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jerry < Formula
  desc "A single binary that scaffolds a repository of Architecture Decision Records and Solution Designs, then owns every rule that governs it."
  homepage "https://github.com/codcod/jerry"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codcod/jerry/releases/download/v0.3.0/jerry_0.3.0_darwin_amd64.tar.gz"
      sha256 "e6cd2502a6ad1a1743b70fed39dcecbd6d14dadd37204a3511fe6a8f986a19bf"

      define_method(:install) do
        bin.install "jerry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codcod/jerry/releases/download/v0.3.0/jerry_0.3.0_darwin_arm64.tar.gz"
      sha256 "24ebd4e864bbfb91db45d5c559e5b45d3a016ad3bf1f454061dcc495a4439d78"

      define_method(:install) do
        bin.install "jerry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/jerry/releases/download/v0.3.0/jerry_0.3.0_linux_amd64.tar.gz"
      sha256 "e6095ddfff55bb454029c7403fdbc814f3813279f0e5f041a98bcf1acd73059e"
      define_method(:install) do
        bin.install "jerry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/jerry/releases/download/v0.3.0/jerry_0.3.0_linux_arm64.tar.gz"
      sha256 "85d46bd748286c6c61691b09fc71bd19b11a990c7af79f4dd5b68bdcf36aea68"
      define_method(:install) do
        bin.install "jerry"
      end
    end
  end
end
