# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jerry < Formula
  desc "A single binary that scaffolds a repository of Architecture Decision Records and Solution Designs, then owns every rule that governs it."
  homepage "https://github.com/codcod/jerry"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codcod/jerry/releases/download/v0.1.0/jerry_0.1.0_darwin_amd64.tar.gz"
      sha256 "55ac35e7d4ec661680f1aa23d65fd682801455716299857a83d639e7674c6edf"

      define_method(:install) do
        bin.install "jerry"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codcod/jerry/releases/download/v0.1.0/jerry_0.1.0_darwin_arm64.tar.gz"
      sha256 "120c7a98fdeace2d0dda99f376b06b859daf665d8bdcf46418e4815e36b7eb02"

      define_method(:install) do
        bin.install "jerry"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/jerry/releases/download/v0.1.0/jerry_0.1.0_linux_amd64.tar.gz"
      sha256 "3e2d308e98cb4f1dea8a564e04fce62a8528f3321631d883e114bd8c630a071d"
      define_method(:install) do
        bin.install "jerry"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/jerry/releases/download/v0.1.0/jerry_0.1.0_linux_arm64.tar.gz"
      sha256 "52e0c7ecea705964c4e8c6690b006fe2789ebbb9976d32de7607bbf33ef1833f"
      define_method(:install) do
        bin.install "jerry"
      end
    end
  end
end
