# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Morty < Formula
  desc "Deterministic Atlassian gateway CLI: Jira issue transport, transitions and snapshots"
  homepage "https://github.com/codcod/morty"
  version "0.3.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codcod/morty/releases/download/v0.3.0/morty_0.3.0_darwin_amd64.tar.gz"
      sha256 "ded3a00bd2778eef98504b35e6d08605be8f4b36efee291ca1688545940daf3e"

      define_method(:install) do
        bin.install "morty"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codcod/morty/releases/download/v0.3.0/morty_0.3.0_darwin_arm64.tar.gz"
      sha256 "3914abdf29723e9ca4a51da5b93f2c57f1d4ede10e670ffbe4ae68c2db83cafe"

      define_method(:install) do
        bin.install "morty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/morty/releases/download/v0.3.0/morty_0.3.0_linux_amd64.tar.gz"
      sha256 "59cef64ed76691e62f87b0c7785099eedbd27fda869c03f894747a3e3615228f"
      define_method(:install) do
        bin.install "morty"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/morty/releases/download/v0.3.0/morty_0.3.0_linux_arm64.tar.gz"
      sha256 "b130df814ffead7d3e240859494fdb981d44031e8067f10181fdcd78df798538"
      define_method(:install) do
        bin.install "morty"
      end
    end
  end
end
