# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Morty < Formula
  desc "Deterministic Atlassian gateway CLI: Jira issue transport, transitions and snapshots"
  homepage "https://github.com/codcod/morty"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codcod/morty/releases/download/v0.1.0/morty_0.1.0_darwin_amd64.tar.gz"
      sha256 "714494ed39f8579b9f1c1f93a1e4c3443c21a985dd2ef7e9206beac305b5c45f"

      define_method(:install) do
        bin.install "morty"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codcod/morty/releases/download/v0.1.0/morty_0.1.0_darwin_arm64.tar.gz"
      sha256 "07d3a2459350e59adb22b6a6fdc786b30c30892af23d7ad573d0eb5fa57f3468"

      define_method(:install) do
        bin.install "morty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/morty/releases/download/v0.1.0/morty_0.1.0_linux_amd64.tar.gz"
      sha256 "1a2309f4c1b4749ca287923a25aca39c88733b7354e8d267487777917255caab"
      define_method(:install) do
        bin.install "morty"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/morty/releases/download/v0.1.0/morty_0.1.0_linux_arm64.tar.gz"
      sha256 "522025cac2e5de2ce4c0b258fa886ca1a1426021a4172d0cd6b3174b8483c76c"
      define_method(:install) do
        bin.install "morty"
      end
    end
  end
end
