# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Morty < Formula
  desc "Deterministic Atlassian gateway CLI: Jira issue transport, transitions and snapshots"
  homepage "https://github.com/codcod/morty"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codcod/morty/releases/download/v0.2.0/morty_0.2.0_darwin_amd64.tar.gz"
      sha256 "b585ec3ec1752bec1ca216284d8f42470aa2e5e1d0972da45f71e84760921419"

      define_method(:install) do
        bin.install "morty"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codcod/morty/releases/download/v0.2.0/morty_0.2.0_darwin_arm64.tar.gz"
      sha256 "27bead2c458c1c07b235407359d4304891073c4ed43cc963c5236ac04c3899ec"

      define_method(:install) do
        bin.install "morty"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/morty/releases/download/v0.2.0/morty_0.2.0_linux_amd64.tar.gz"
      sha256 "6c72c514c03f2da87ad74c9c87548e06d6aacf9a0a3a3b91a709c9ead2083abc"
      define_method(:install) do
        bin.install "morty"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/morty/releases/download/v0.2.0/morty_0.2.0_linux_arm64.tar.gz"
      sha256 "523669431cc7f64f804caae034d85c022b76671effed6721c16a8355797ed719"
      define_method(:install) do
        bin.install "morty"
      end
    end
  end
end
