# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pickle < Formula
  desc "Ticket-based, board-driven feature flow as a CLI"
  homepage "https://github.com/codcod/pickle"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codcod/pickle/releases/download/v0.2.1/pickle_0.2.1_darwin_amd64.tar.gz"
      sha256 "871d231025297621383ba139a60b6bba861f52e85235368e371584ff4668f08d"

      define_method(:install) do
        bin.install "pickle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codcod/pickle/releases/download/v0.2.1/pickle_0.2.1_darwin_arm64.tar.gz"
      sha256 "9a617b86b502d1657fc75d27ad31081e2c62d9ac9f75e2ac1c7b7788b0c737dd"

      define_method(:install) do
        bin.install "pickle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/pickle/releases/download/v0.2.1/pickle_0.2.1_linux_amd64.tar.gz"
      sha256 "694202c2fb90801b4eb068fcdd0717ab2576c64745627b00ff2460e5f7da048e"
      define_method(:install) do
        bin.install "pickle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/pickle/releases/download/v0.2.1/pickle_0.2.1_linux_arm64.tar.gz"
      sha256 "a4ec66d02aad5c654b3ca9b2a0740f9581f2aa1f78a5d08d3358ee814c0226d8"
      define_method(:install) do
        bin.install "pickle"
      end
    end
  end
end
