# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pickle < Formula
  desc "Ticket-based, board-driven feature flow as a CLI"
  homepage "https://github.com/codcod/pickle"
  version "0.2.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codcod/pickle/releases/download/v0.2.1/pickle_0.2.1_darwin_amd64.tar.gz"
      sha256 "9a1c6e85e575a16cce9d97a766d3e3051642a6a60bd5c7986447abcba4574011"

      define_method(:install) do
        bin.install "pickle"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codcod/pickle/releases/download/v0.2.1/pickle_0.2.1_darwin_arm64.tar.gz"
      sha256 "914425269bd716c3b46463572216ec369f5f400fec24389fd956cf14549360c1"

      define_method(:install) do
        bin.install "pickle"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/pickle/releases/download/v0.2.1/pickle_0.2.1_linux_amd64.tar.gz"
      sha256 "e49ecff5f1ee4d56c5aed3130928b336c527871bcfc6419ffca1cbb191e0db2f"
      define_method(:install) do
        bin.install "pickle"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/pickle/releases/download/v0.2.1/pickle_0.2.1_linux_arm64.tar.gz"
      sha256 "8cfd51b99a34afd127a113dfd42a2ff64f3de75a739e92230350cc16f15fb72e"
      define_method(:install) do
        bin.install "pickle"
      end
    end
  end
end
