# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snowball < Formula
  desc "Render AsciiDoc books to PDF/EPUB via the native asciidoctor toolchain"
  homepage "https://github.com/codcod/snowball"
  version "0.4.0"

  depends_on "node"
  depends_on "ruby"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codcod/snowball/releases/download/v0.4.0/snowball_0.4.0_darwin_amd64.tar.gz"
      sha256 "35c112da908c2210e3bab05e6b3a605138cf1a215e873f70ea780262116bd531"

      define_method(:install) do
        bin.install "snowball"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codcod/snowball/releases/download/v0.4.0/snowball_0.4.0_darwin_arm64.tar.gz"
      sha256 "f272554a84c9c6685e2ff679c3db127ea019d9ac5ea6d5aaebd10179ad41bf67"

      define_method(:install) do
        bin.install "snowball"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/snowball/releases/download/v0.4.0/snowball_0.4.0_linux_amd64.tar.gz"
      sha256 "bef2391741b6e5a8269c36ac0402be88329426f2e1c6d8b9759ce796db2ca433"
      define_method(:install) do
        bin.install "snowball"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/snowball/releases/download/v0.4.0/snowball_0.4.0_linux_arm64.tar.gz"
      sha256 "f9ea6f2e2bd24906dbdd83e56cebe34b7a888d537ea4a47897eaf896ac0cb148"
      define_method(:install) do
        bin.install "snowball"
      end
    end
  end

  def caveats
    <<~EOS
      Run `snowball setup` once to install the pinned gems, mermaid-cli, and Chrome.
    EOS
  end
end
