# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Snowball < Formula
  desc "Render AsciiDoc books to PDF/EPUB via the native asciidoctor toolchain"
  homepage "https://github.com/codcod/snowball"
  version "0.3.0"

  depends_on "node"
  depends_on "ruby"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codcod/snowball/releases/download/v0.3.0/snowball_0.3.0_darwin_amd64.tar.gz"
      sha256 "229ed9fa9ea21baf6c8ed91486bb281f708dc438770eb7c50288fd2be18ca221"

      define_method(:install) do
        bin.install "snowball"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codcod/snowball/releases/download/v0.3.0/snowball_0.3.0_darwin_arm64.tar.gz"
      sha256 "91fb7727b7384e3b9311f9da558078a6880626bacff8c3bb7b0e1ef35e162377"

      define_method(:install) do
        bin.install "snowball"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/snowball/releases/download/v0.3.0/snowball_0.3.0_linux_amd64.tar.gz"
      sha256 "04c3d137fedc97a3ad045661a3987af0c5b3d2e4faf51badac1468894abffd68"
      define_method(:install) do
        bin.install "snowball"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/snowball/releases/download/v0.3.0/snowball_0.3.0_linux_arm64.tar.gz"
      sha256 "9f569d72e9a29ebab45a9136ae058a680430a55dc0976f8b58c5d7d7ab9dccc7"
      define_method(:install) do
        bin.install "snowball"
      end
    end
  end

  def caveats
    <<~EOS
      Run `snowball setup` once to install the pinned gems, mermaid-cli, and Chrome.
    EOS
  end
end
