# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Summer < Formula
  desc "LLM-driven agile-coaching assistant for Jira refinement, planning and review prep"
  homepage "https://github.com/codcod/summer"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codcod/summer/releases/download/v0.1.0/summer_0.1.0_darwin_amd64.tar.gz"
      sha256 "d6ab07c12295bcd74e9ec888e7478b59c7d8024bb5efac42a6b2b1ed26628f61"

      define_method(:install) do
        bin.install "summer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codcod/summer/releases/download/v0.1.0/summer_0.1.0_darwin_arm64.tar.gz"
      sha256 "711980e4a8822254f8ebc49b41d74a79a57fe6b38086f7d5b6977f18b32e65a8"

      define_method(:install) do
        bin.install "summer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/summer/releases/download/v0.1.0/summer_0.1.0_linux_amd64.tar.gz"
      sha256 "bce0c980fd3055ef448ccc72cc5f62dcdf78e07dc9b95457a996acebc3845da5"
      define_method(:install) do
        bin.install "summer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/summer/releases/download/v0.1.0/summer_0.1.0_linux_arm64.tar.gz"
      sha256 "ae286a8ac530efa3cb73e3a038054172cbffcf1356dbeec83fb715ef755fb6f1"
      define_method(:install) do
        bin.install "summer"
      end
    end
  end
end
