# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Summer < Formula
  desc "LLM-driven agile-coaching assistant for Jira refinement, planning and review prep"
  homepage "https://github.com/codcod/summer"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/codcod/summer/releases/download/v0.2.0/summer_0.2.0_darwin_amd64.tar.gz"
      sha256 "9dcec15960a7154504d0d382ea245d01a4fbc80104d841041644663c3d6da5f0"

      define_method(:install) do
        bin.install "summer"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/codcod/summer/releases/download/v0.2.0/summer_0.2.0_darwin_arm64.tar.gz"
      sha256 "9ef1f91d5f97470361d51f276a25838d431deea84a4db264df953520f3f24c0d"

      define_method(:install) do
        bin.install "summer"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/summer/releases/download/v0.2.0/summer_0.2.0_linux_amd64.tar.gz"
      sha256 "351da2f2ba6ea8db35b83e6ca7c1a61213ad5243201ef5791bebfe5e71285ad1"
      define_method(:install) do
        bin.install "summer"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/codcod/summer/releases/download/v0.2.0/summer_0.2.0_linux_arm64.tar.gz"
      sha256 "81d7bc972e57c21b0225c231456b97038a7d69f48b769802d137cff72644e7bb"
      define_method(:install) do
        bin.install "summer"
      end
    end
  end
end
