# This file was generated by GoReleaser. DO NOT EDIT.
cask "snowball" do
  version "0.1.3"

  on_macos do
    on_intel do
      sha256 "d74052f4aaabacd83d8c031b59cb061535dee052e2e95d8c6fed9430e57e5034"
      url "https://github.com/codcod/snowball/releases/download/v#{version}/snowball_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2ced41be5208b66783d8ecb2fcaa4b800150d8883826b91f39aef40d2b5bd23f"
      url "https://github.com/codcod/snowball/releases/download/v#{version}/snowball_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2421c97786683ec95e5be677645c07a676993a08ca0bb58ab632434a3c3962b4"
      url "https://github.com/codcod/snowball/releases/download/v#{version}/snowball_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a5933052fcaf890877435a6314f87a5c1d40f513f337acc8e991f511e594cd31"
      url "https://github.com/codcod/snowball/releases/download/v#{version}/snowball_#{version}_linux_arm64.tar.gz"
    end
  end

  name "snowball"
  desc "Render AsciiDoc books to PDF/EPUB via the native asciidoctor toolchain"
  homepage "https://github.com/codcod/snowball"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "node",
      "ruby",
    ]

  binary "snowball"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/snowball"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Run `snowball setup` once to install the pinned gems, mermaid-cli, and Chrome.
  EOS
end
